-- mappatura_alias_gestionale.sql - NON e' una migration.
--
-- Si esegue nell'SQL Editor DOPO aver caricato l'export completo
-- (elencoAnagraficaFormazioni.xlsx) da back-office -> Regole app ->
-- Alias corsi -> Applica. Prima di quel passo le righe non esistono e
-- ogni update tocca 0 righe (innocuo, ma non fa nulla).
--
-- Idempotente: si puo' rieseguire. Non ASCII-only per forza di cose --
-- il testo deve combaciare CARATTERE PER CARATTERE con quello caricato
-- dal parser, apostrofi tipografici e lettere accentate compresi.
-- Il conteggio finale dice se qualcosa non ha combaciato.

begin;

-- AI_LIV1  (2 alias)
update corso_alias set corso_codice = 'AI_LIV1', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO PREVENZIONE INCENDIO, LOTTA ANTINCENDIO E GESTIONE DELL’EMERGENZA IN ATTIVITÀ A RISCHIO D’INCENDIO BASSO',
   'CORSO DI FORMAZIONE ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 1'
 );

-- AI_LIV1 - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'AI_LIV1', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO PREVENZIONE INCENDIO, LOTTA ANTINCENDIO E GESTIONE DELL’EMERGENZA IN ATTIVITÀ A RISCHIO D’INCENDIO BASSO',
   'CORSO DI AGGIORNAMENTO ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 1'
 );

-- AI_LIV2  (2 alias)
update corso_alias set corso_codice = 'AI_LIV2', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO PREVENZIONE INCENDIO, LOTTA ANTINCENDIO E GESTIONE DELL’EMERGENZA IN ATTIVITÀ A RISCHIO D’INCENDIO MEDIO',
   'CORSO DI FORMAZIONE ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 2'
 );

-- AI_LIV2 - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'AI_LIV2', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO PREVENZIONE INCENDIO, LOTTA ANTINCENDIO E GESTIONE DELL’EMERGENZA IN ATTIVITÀ A RISCHIO D’INCENDIO MEDIO',
   'CORSO DI AGGIORNAMENTO ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 2'
 );

-- AI_LIV3  (2 alias)
update corso_alias set corso_codice = 'AI_LIV3', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO ANTINCENDIO RISCHIO ALTO',
   'CORSO DI FORMAZIONE ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 3'
 );

-- AI_LIV3 - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'AI_LIV3', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ANTINCENDIO RISCHIO ALTO',
   'CORSO DI AGGIORNAMENTO ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 3'
 );

-- ATTR_AMB_CONFINATI  (5 alias)
update corso_alias set corso_codice = 'ATTR_AMB_CONFINATI', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO A LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO',
   'ADDETTO AI LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO',
   'CORSO PER ADDETTI AI LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO',
   'CORSO PER ADDETTI AI LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO- ASR 2025',
   'CORSO PER LAVORATORI, DATORI DI LAVORO E LAVORATORI AUTONOMI CHE OPERANO IN AMBIENTI SOSPETTI DI INQUINAMENTO O CONFINATI'
 );

-- ATTR_AMB_CONFINATI - AGGIORNAMENTO  (5 alias)
update corso_alias set corso_codice = 'ATTR_AMB_CONFINATI', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO PER LAVORATORI, DATORI DI LAVORO E LAVORATORI AUTONOMI CHE OPERANO IN AMBIENTI SOSPETTI DI INQUINAMENTO O CONFINATI',
   'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO LAVORATORI)',
   'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO PREPOSTO)',
   'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO)',
   'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO R.S.P.P. MODULO B)'
 );

-- ATTR_AUTORIBALTABILI  (2 alias)
update corso_alias set corso_codice = 'ATTR_AUTORIBALTABILI', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI AUTORIBALTABILI A CINGOLI',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI AUTORIBALTABILI A CINGOLI'
 );

-- ATTR_AUTORIBALTABILI - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'ATTR_AUTORIBALTABILI', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI AUTORIBALTABILI A CINGOLI',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI AUTORIBALTABILI A CINGOLI'
 );

-- ATTR_CARRELLO  (9 alias)
update corso_alias set corso_codice = 'ATTR_CARRELLO', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)',
   'ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, CARRELLI SEMOVENTI A BRACCIO TELESCOPICO, CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)',
   'ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI SEMOVENTI A BRACCIO TELESCOPICO)',
   'ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, SEMOVENTI A BRACCIO TELESCOPICO E CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI SEMOVENTI A BRACCIO TELESCOPICO)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)',
   'FORMAZIONE ADDETTI ALLA CONDUZIONE CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, SEMOVENTI A BRACCIO TELESCOPICO, CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI SOLLEVAMENTO CARICHI SOSPESI/PERSONE)'
 );

-- ATTR_CARRELLO - EVIDENZA PREGRESSA  (1 alias)
update corso_alias set corso_codice = 'ATTR_CARRELLO', is_aggiornamento = false, pregressa = true, parziale = false, ignorato = false
 where testo_gestionale in (
   'PRE ASR_2015_ ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)'
 );

-- ATTR_CARRELLO - AGGIORNAMENTO  (9 alias)
update corso_alias set corso_codice = 'ATTR_CARRELLO', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTI ALLA CONDUZIONE CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, SEMOVENTI A BRACCIO TELESCOPICO, CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI SOLLEVAMENTO CARICHI SOSPESI/PERSONE)',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, CARRELLI SEMOVENTI A BRACCIO TELESCOPICO, CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI SEMOVENTI A BRACCIO TELESCOPICO)',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, CARRELLI SEMOVENTI A BRACCIO TELESCOPICO E CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI SEMOVENTI A BRACCIO TELESCOPICO)',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)'
 );

-- ATTR_CARROPONTE  (7 alias)
update corso_alias set corso_codice = 'ATTR_CARROPONTE', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI CARROPONTE E GRU A BANDIERA',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO IN CABINA',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO PENSILE/RADIOCOMANDO',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO PENSILE/RADIOCOMANDO E/O CON COMANDO IN CABINA',
   'CORSO PER ADDETTO ALLA CONDUZIONE DI CARROPONTE',
   'CORSO PER ADDETTO ALLA CONDUZIONE DI CARROPONTE (GRU A PONTE)',
   'FORMAZIONE ADDETTO ALLA CONDUZIONE DI CARROPONTE (GRU CARROPONTE/ GRU A CAVALLETTO CON COMANDO PENSILE/RADIOCOMANDATO)'
 );

-- ATTR_CARROPONTE - AGGIORNAMENTO  (6 alias)
update corso_alias set corso_codice = 'ATTR_CARROPONTE', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARROPONTE (GRU A PONTE)',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARROPONTE E GRU A BANDIERA',
   'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO IN CABINA',
   'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO PENSILE/RADIOCOMANDO',
   'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO PENSILE/RADIOCOMANDO E/O CON COMANDO IN CABINA',
   'CORSO DI AGGIORNAMENTO PER ADDETTO ALLA CONDUZIONE DI CARROPONTE'
 );

-- ATTR_CMM  (1 alias)
update corso_alias set corso_codice = 'ATTR_CMM', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARICATORI PER LA MOVIMENTAZIONE DI MATERIALI (CMM)'
 );

-- ATTR_CMM - AGGIORNAMENTO  (1 alias)
update corso_alias set corso_codice = 'ATTR_CMM', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI CARICATORI PER LA MOVIMENTAZIONE DI MATERIALI (CMM)'
 );

-- ATTR_CRF  (1 alias)
update corso_alias set corso_codice = 'ATTR_CRF', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI MACCHINA AGRICOLA RACCOGLIFRUTTA (COMUNEMENTE DETTA CARRO RACCOGLIFRUTTA CRF)'
 );

-- ATTR_CRF - AGGIORNAMENTO  (1 alias)
update corso_alias set corso_codice = 'ATTR_CRF', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI MACCHINA AGRICOLA RACCOGLIFRUTTA (COMUNEMENTE DETTA CARRO RACCOGLIFRUTTA CRF)'
 );

-- ATTR_ESCAVATORI  (10 alias)
update corso_alias set corso_codice = 'ATTR_ESCAVATORI', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI ESCAVATORI A FUNE',
   'ADDETTO ALLA CONDUZIONE DI ESCAVATORI IDRAULICI',
   'ADDETTO ALLA CONDUZIONE DI ESCAVATORI IDRAULICI, CARICATORI FRONTALI E TERNE',
   'ADDETTO ALLA CONDUZIONE DI PALE CARICATRICI FRONTALI',
   'ADDETTO ALLA CONDUZIONE DI TERNE',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI A FUNE',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI IDRAULICI',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI IDRAULICI, CARICATORI FRONTALI E TERNE',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PALE CARICATRICI FRONTALI',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TERNE'
 );

-- ATTR_ESCAVATORI - AGGIORNAMENTO  (10 alias)
update corso_alias set corso_codice = 'ATTR_ESCAVATORI', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI ESCAVATORI A FUNE',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI ESCAVATORI IDRAULICI',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI ESCAVATORI IDRAULICI, CARICATORI FRONTALI E TERNE',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI PALE CARICATRICI FRONTALI',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI TERNE',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI A FUNE',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI IDRAULICI',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI IDRAULICI, CARICATORI FRONTALI E TERNE',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PALE CARICATRICI FRONTALI',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TERNE'
 );

-- ATTR_GRU_AUTOCARRO  (2 alias)
update corso_alias set corso_codice = 'ATTR_GRU_AUTOCARRO', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI GRU PER AUTOCARRO',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU PER AUTOCARRO'
 );

-- ATTR_GRU_AUTOCARRO - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'ATTR_GRU_AUTOCARRO', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU PER AUTOCARRO',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU PER AUTOCARRO'
 );

-- ATTR_GRU_MOBILI  (4 alias)
update corso_alias set corso_codice = 'ATTR_GRU_MOBILI', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI GRU MOBILI - CORSO BASE (PER GRU MOBILI AUTOCARRATE E SEMOVENTI SU RUOTE CON BRACCIO TELESCOPICO O TRALICCIATO ED EVENTUALE FALCONE FISSO)',
   'ADDETTO ALLA CONDUZIONE DI GRU MOBILI - CORSO BASE E MODULO AGGIUNTIVO (PER GRU MOBILI SU RUOTE CON FALCONE TELESCOPICO O BRANDEGGIABILE)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU MOBILI-MODULO BASE E MODULO AGGIUNTIVO PER LE GRU MOBILI SU RUOTE CON FALCONE TELESCOPICO O BRANDEGGIABILE',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU MOBILI-MODULO BASE PER GRU MOBILI AUTOCARRATE E SEMOVENTI SU RUOTE CON BRACCIO TELESCOPICO O TRALICCIATO ED EVENTUALE FALCONE FISSO'
 );

-- ATTR_GRU_MOBILI - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'ATTR_GRU_MOBILI', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU MOBILI',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU MOBILI'
 );

-- ATTR_GRU_TORRE  (6 alias)
update corso_alias set corso_codice = 'ATTR_GRU_TORRE', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN ALTO)',
   'ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN BASSO E GRU A ROTAZIONE IN ALTO)',
   'ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN BASSO)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN ALTO',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN BASSO',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN BASSO E IN ALTO'
 );

-- ATTR_GRU_TORRE - AGGIORNAMENTO  (6 alias)
update corso_alias set corso_codice = 'ATTR_GRU_TORRE', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN ALTO)',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN BASSO E GRU A ROTAZIONE IN ALTO)',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN BASSO)',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN ALTO',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN BASSO',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN BASSO E IN ALTO'
 );

-- ATTR_LAV_ELETTRICI  (2 alias)
update corso_alias set corso_codice = 'ATTR_LAV_ELETTRICI', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO PES, PAV, PEI PER ADDETTI AI LAVORI ELETTRICI – NUOVA NORMA CEI 11-27 EDIZIONE 2021',
   'PEI, PES E PAV OPERATORI SU QUADRI ELETTRICI'
 );

-- ATTR_LAV_ELETTRICI - AGGIORNAMENTO  (1 alias)
update corso_alias set corso_codice = 'ATTR_LAV_ELETTRICI', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO PES E PAV OPERATORI SU QUADRI ELETTRICI'
 );

-- ATTR_LAV_QUOTA  (5 alias)
update corso_alias set corso_codice = 'ATTR_LAV_QUOTA', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO DI FORMAZIONE LAVORI IN QUOTA',
   'CORSO DI FORMAZIONE LAVORI IN QUOTA E DPI 3* CAT. ANTICADUTA + SCALE/TRABATTELLO',
   'CORSO DI FORMAZIONE LAVORI IN QUOTA E DPI 3°CAT. ANTICADUTA',
   'CORSO PER ADDETTI AI LAVORI IN QUOTA E ALL''UTILIZZO DI SCALE PORTATILI E FISSE',
   'SVOLGIMENTO DI ATTIVITA'' IN QUOTA PER LAVORATORI ADDETTI ALL''INSTALLAZIONE E MANUTENZIONE DI PANNELLI FV'
 );

-- ATTR_LAV_QUOTA - AGGIORNAMENTO  (1 alias)
update corso_alias set corso_codice = 'ATTR_LAV_QUOTA', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO FORMAZIONE LAVORI IN QUOTA E DPI 3°CAT. ANTICADUTA'
 );

-- ATTR_PLE  (8 alias)
update corso_alias set corso_codice = 'ATTR_PLE', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON E SENZA STABILIZZATORI)',
   'ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON STABILIZZATORI)',
   'ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE SENZA STABILIZZATORI)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) CON E SENZA STABILIZZATORI',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) SENZA STABILIZZATORI',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) SU STABILIZZATORI',
   'INTEGRAZIONE ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON STABILIZZATORI)',
   'INTEGRAZIONE ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE SENZA STABILIZZATORI)'
 );

-- ATTR_PLE - AGGIORNAMENTO  (6 alias)
update corso_alias set corso_codice = 'ATTR_PLE', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON E SENZA STABILIZZATORI)',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON STABILIZZATORI)',
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE SENZA STABILIZZATORI)',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) CON E SENZA STABILIZZATORI',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) SENZA STABILIZZATORI',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) SU STABILIZZATORI'
 );

-- ATTR_POMPE_CLS  (2 alias)
update corso_alias set corso_codice = 'ATTR_POMPE_CLS', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI POMPE PER CALCESTRUZZO',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI POMPE PER CALCESTRUZZO'
 );

-- ATTR_POMPE_CLS - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'ATTR_POMPE_CLS', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI POMPE PER CALCESTRUZZO',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI POMPE PER CALCESTRUZZO'
 );

-- ATTR_TRATT_CINGOLI  (2 alias)
update corso_alias set corso_codice = 'ATTR_TRATT_CINGOLI', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A CINGOLI)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A CINGOLI'
 );

-- ATTR_TRATT_CINGOLI - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'ATTR_TRATT_CINGOLI', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A CINGOLI)',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A CINGOLI'
 );

-- ATTR_TRATT_RUOTE  (2 alias)
update corso_alias set corso_codice = 'ATTR_TRATT_RUOTE', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A RUOTE)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A RUOTE'
 );

-- ATTR_TRATT_RUOTE - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'ATTR_TRATT_RUOTE', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A RUOTE)',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A RUOTE'
 );

-- ATTR_TRATT_RUOTE_CINGOLI  (2 alias)
update corso_alias set corso_codice = 'ATTR_TRATT_RUOTE_CINGOLI', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A CINGOLI E RUOTE)',
   'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A RUOTE E A CINGOLI'
 );

-- ATTR_TRATT_RUOTE_CINGOLI - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'ATTR_TRATT_RUOTE_CINGOLI', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A CINGOLI E RUOTE)',
   'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A RUOTE E A CINGOLI'
 );

-- CANTIERI  (2 alias)
update corso_alias set corso_codice = 'CANTIERI', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'MODULO AGGIUNTIVO “CANTIERI” PER DATORI DI LAVORO',
   'MODULO AGGIUNTIVO “CANTIERI” PER DIRIGENTE'
 );

-- DATORE_LAVORO  (2 alias)
update corso_alias set corso_codice = 'DATORE_LAVORO', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'DATORE DI LAVORO',
   'DATORE DI LAVORO CON MODULO AGGIUNTIVO “CANTIERI”'
 );

-- DATORE_LAVORO - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'DATORE_LAVORO', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO DATORE DI LAVORO',
   'AGGIORNAMENTO DATORE DI LAVORO CON MODULO AGGIUNTIVO “CANTIERI”'
 );

-- DIRIGENTE  (3 alias)
update corso_alias set corso_codice = 'DIRIGENTE', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO PER DIRIGENTE',
   'CORSO PER DIRIGENTE CON MODULO AGGIUNTIVO CANTIERI',
   'DIRIGENTI'
 );

-- DIRIGENTE - AGGIORNAMENTO  (3 alias)
update corso_alias set corso_codice = 'DIRIGENTE', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO DIRIGENTI',
   'CORSO DI AGGIORNAMENTO DIRIGENTE',
   'CORSO DI AGGIORNAMENTO DIRIGENTE CON MODULO AGGIUNTIVO CANTIERI'
 );

-- DL_RSPP_BASE  (6 alias)
update corso_alias set corso_codice = 'DL_RSPP_BASE', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'INTEGRAZIONE R.S.P.P. DATORE DI LAVORO MODULO 3 E 4 - RISCHIO ALTO',
   'INTEGRAZIONE R.S.P.P. DATORE DI LAVORO MODULO 3 E 4 - RISCHIO BASSO',
   'INTEGRAZIONE R.S.P.P. DATORE DI LAVORO MODULO 3 E 4 - RISCHIO MEDIO',
   'R.S.P.P. DATORE DI LAVORO RISCHIO ALTO',
   'R.S.P.P. DATORE DI LAVORO RISCHIO BASSO',
   'R.S.P.P. DATORE DI LAVORO RISCHIO MEDIO'
 );

-- DL_RSPP_BASE - AGGIORNAMENTO  (4 alias)
update corso_alias set corso_codice = 'DL_RSPP_BASE', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP',
   'AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO RISCHIO ALTO',
   'AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO RISCHIO BASSO',
   'AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO RISCHIO MEDIO'
 );

-- DL_RSPP_BASE - AGGIORNAMENTO - SPEZZONE (parziale)  (1 alias)
update corso_alias set corso_codice = 'DL_RSPP_BASE', is_aggiornamento = true, pregressa = false, parziale = true, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO PARZIALE PER RSPP DATORE DI LAVORO RISCHIO ALTO'
 );

-- DL_RSPP_COMUNE  (1 alias)
update corso_alias set corso_codice = 'DL_RSPP_COMUNE', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP MODULO COMUNE'
 );

-- DL_RSPP_SETTORE  (4 alias)
update corso_alias set corso_codice = 'DL_RSPP_SETTORE', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'MODULO INTEGRATIVO 1: AGRICOLTURA – SILVICOLTURA - ZOOTECNIA PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP',
   'MODULO INTEGRATIVO 2: PESCA PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP',
   'MODULO INTEGRATIVO 3: COSTRUZIONI PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP',
   'MODULO INTEGRATIVO 4: CHIMICO - PETROLCHIMICO PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP'
 );

-- LAV_GEN  (1 alias)
update corso_alias set corso_codice = 'LAV_GEN', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'FORMAZIONE DEI LAVORATORI (GENERALE)'
 );

-- LAV_SPEC  (11 alias)
update corso_alias set corso_codice = 'LAV_SPEC', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'FORMAZIONE DEI LAVORATORI RISCHIO BASSO',
   'FORMAZIONE LAVORATORI RISCHIO ALTO',
   'FORMAZIONE LAVORATORI RISCHIO ALTO - SPECIFICA',
   'FORMAZIONE LAVORATORI RISCHIO BASSO',
   'FORMAZIONE LAVORATORI RISCHIO BASSO - SPECIFICA',
   'FORMAZIONE LAVORATORI RISCHIO MEDIO',
   'FORMAZIONE LAVORATORI RISCHIO MEDIO - SPECIFICA',
   'INTEGRAZIONE FORMAZIONE SPECIFICA LAVORATORI - RISCHIO ALTO',
   'INTEGRAZIONE FORMAZIONE SPECIFICA LAVORATORI- RISCHIO ALTO',
   'INTEGRAZIONE FORMAZIONE SPECIFICA LAVORATORI-RISCHIO ALTO',
   'INTEGRAZIONE FORMAZIONE SPECIFICA LAVORATORI-RISCHIO MEDIO'
 );

-- LAV_SPEC - SPEZZONE (parziale)  (2 alias)
update corso_alias set corso_codice = 'LAV_SPEC', is_aggiornamento = false, pregressa = false, parziale = true, ignorato = false
 where testo_gestionale in (
   'FORMAZIONE SPECIFICA RISCHIO ALTO PARZIALE 6H 1\2',
   'FORMAZIONE SPECIFICA RISCHIO ALTO, PARZIALE 6H 2/2'
 );

-- LAV_SPEC - AGGIORNAMENTO  (5 alias)
update corso_alias set corso_codice = 'LAV_SPEC', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO FORMAZIONE DEI LAVORATORI RISCHIO ALTO',
   'AGGIORNAMENTO FORMAZIONE DEI LAVORATORI RISCHIO BASSO',
   'AGGIORNAMENTO FORMAZIONE DEI LAVORATORI RISCHIO MEDIO',
   'AGGIORNAMENTO LAVORATORI - 6 ORE - EDILIZIA',
   'AGGIORNAMENTO LAVORATORI 6 ORE'
 );

-- LAV_SPEC - AGGIORNAMENTO - SPEZZONE (parziale)  (2 alias)
update corso_alias set corso_codice = 'LAV_SPEC', is_aggiornamento = true, pregressa = false, parziale = true, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO PARZIALE PER LAVORATORI',
   'AGGIORNAMENTO PARZIALE PER LAVORATORI - APERITIVO'
 );

-- PONTEGGI  (2 alias)
update corso_alias set corso_codice = 'PONTEGGI', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO AL MONTAGGIO, SMONTAGGIO, TRASFORMAZIONE DI PONTEGGI O PER PREPOSTI ALLA SORVEGLIANZA',
   'LAVORATORI E PREPOSTI ADDETTI AL MONTAGGIO, SMONTAGGIO E TRASFORMAZIONE DI PONTEGGI, USO DPI ANTICADUTA'
 );

-- PONTEGGI - AGGIORNAMENTO  (1 alias)
update corso_alias set corso_codice = 'PONTEGGI', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO AL MONTAGGIO, SMONTAGGIO, TRASFORMAZIONE DI PONTEGGI O PER PREPOSTI ALLA SORVEGLIANZA'
 );

-- PREPOSTO  (5 alias)
update corso_alias set corso_codice = 'PREPOSTO', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO DI FORMAZIONE PER PREPOSTI',
   'FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI',
   'FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI - BIENNALE',
   'FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI_BIENNALE',
   'INTEGRAZIONE FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI'
 );

-- PREPOSTO - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'PREPOSTO', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO LAVORATORI PREPOSTI',
   'CORSO DI AGGIORNAMENTO PER PREPOSTI'
 );

-- PS_BLSD_LAICO  (3 alias)
update corso_alias set corso_codice = 'PS_BLSD_LAICO', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'BLS-D (BASIC LIFE SUPPORT AND DEFIBRILLATION) (LAICO)',
   'BLS-D (BASIC LIFE SUPPORT AND DEFIBRILLATION) LAICO',
   'ESECUTORE BLSD - CATEGORIA B'
 );

-- PS_BLSD_LAICO - AGGIORNAMENTO  (1 alias)
update corso_alias set corso_codice = 'PS_BLSD_LAICO', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO BLS-D (BASIC LIFE SUPPORT AND DEFIBRILLATION) LAICO'
 );

-- PS_BLSD_SANITARIO  (1 alias)
update corso_alias set corso_codice = 'PS_BLSD_SANITARIO', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'BLS-D (BASIC LIFE SUPPORT AND DEFIBRILLATION) PER SANITARI'
 );

-- PS_GRA  (1 alias)
update corso_alias set corso_codice = 'PS_GRA', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO A'
 );

-- PS_GRA - AGGIORNAMENTO  (1 alias)
update corso_alias set corso_codice = 'PS_GRA', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO A'
 );

-- PS_GRBC  (1 alias)
update corso_alias set corso_codice = 'PS_GRBC', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO B-C'
 );

-- PS_GRBC - AGGIORNAMENTO  (1 alias)
update corso_alias set corso_codice = 'PS_GRBC', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO B-C'
 );

-- RLS  (1 alias)
update corso_alias set corso_codice = 'RLS', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'R.L.S.'
 );

-- RLS - AGGIORNAMENTO  (2 alias)
update corso_alias set corso_codice = 'RLS', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO R.L.S. 4 ORE',
   'AGGIORNAMENTO R.L.S. 8 ORE'
 );

-- RLS - AGGIORNAMENTO - SPEZZONE (parziale)  (2 alias)
update corso_alias set corso_codice = 'RLS', is_aggiornamento = true, pregressa = false, parziale = true, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO PARZIALE PER R.L.S.',
   'AGGIORNAMENTO PARZIALE PER RLS'
 );

-- RSPP_MOD_A  (2 alias)
update corso_alias set corso_codice = 'RSPP_MOD_A', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO RSPP / ASPP MODULO A',
   'R.S.P.P. / A.S.P.P. - MODULO A - A.S.R. 2016'
 );

-- RSPP_MOD_B  (3 alias)
update corso_alias set corso_codice = 'RSPP_MOD_B', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO RSPP / ASPP MODULO B COMUNE',
   'R.S.P.P. / A.S.P.P. MODULO B COMUNE',
   'R.S.P.P. / A.S.P.P. MODULO B'
 );

-- RSPP_MOD_B - AGGIORNAMENTO  (5 alias)
update corso_alias set corso_codice = 'RSPP_MOD_B', is_aggiornamento = true, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'AGGIORNAMENTO A.S.P.P. A.S.R. 2016',
   'AGGIORNAMENTO ASPP',
   'AGGIORNAMENTO R.S.P.P. A.S.R. 2016',
   'AGGIORNAMENTO R.SP.P./A.S.P.P. - MODULO B',
   'AGGIORNAMENTO RSPP'
 );

-- RSPP_MOD_B_SETTORE  (9 alias)
update corso_alias set corso_codice = 'RSPP_MOD_B_SETTORE', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'MODULO B DI SPECIALIZZAZIONE SP1: AGRICOLTURA – SILVICOLTURA - ZOOTECNIA PER RSPP/ASPP',
   'MODULO B DI SPECIALIZZAZIONE SP2: PESCA PER RSPP/ASPP',
   'MODULO B DI SPECIALIZZAZIONE SP3: COSTRUZIONI PER RSPP/ASPP',
   'MODULO B DI SPECIALIZZAZIONE SP4: SANITÀ RESIDENZIALE PER RSPP/ASPP',
   'MODULO B DI SPECIALIZZAZIONE SP5: CHIMICO - PETROLCHIMICO PER RSPP/ASPP',
   'R.S.P.P. / A.S.P.P. MODULO B-SP1: AGRICOLTURA - PESCA',
   'R.S.P.P. / A.S.P.P. MODULO B-SP2: ATTIVITÀ ESTRATTIVE- COSTRUZIONI',
   'R.S.P.P. / A.S.P.P. MODULO B-SP3: SANITÀ RESIDENZIALE',
   'R.S.P.P. / A.S.P.P. MODULO B-SP4: CHIMICO - PETROLCHIMICO'
 );

-- RSPP_MOD_C  (2 alias)
update corso_alias set corso_codice = 'RSPP_MOD_C', is_aggiornamento = false, pregressa = false, parziale = false, ignorato = false
 where testo_gestionale in (
   'CORSO RSPP MODULO C',
   'R.S.P.P. - MODULO C - A.S.R. 2016'
 );

-- IGNORATI - fuori dal perimetro ASR/organigramma (31 alias)
update corso_alias set ignorato = true
 where testo_gestionale in (
   'ADDETTO GESTIONE DELLA QUALITA''',
   'ADDETTO LAVORI IN AMBIENTI SOSPETTI DI PRESENZA AMIANTO',
   'ADDETTO PREPOSTO UTILIZZO DELLA SEGNALETICA STRADALE',
   'ADDETTO UTILIZZO DELLA SEGNALETICA STRADALE',
   'AGG. FORMAZIONE PER L''USO DEI DIISOCIANATI - LIVELLO GENERALE, INTERMEDIO E AVANZATO',
   'AGGIORNAMENTO ADDETTO LAVORATORE E PREPOSTO UTILIZZO DELLA SEGNALETICA STRADALE',
   'AGGIORNAMENTO COORDINATORE DELLA SICUREZZA NEI CANTIERI TEMPORANEI O MOBILI',
   'AGGIORNAMENTO COORDINATORI PER LA PROGETTAZIONE E PER L’ESECUZIONE DEI LAVORI',
   'APPALTI E SUBAPPALTI',
   'COORDINATORE DELLA SICUREZZA NEI CANTIERI TEMPORANEI O MOBILI',
   'CORSO ABC RIFIUTI',
   'CORSO ADEMPIMENTI E OBBLIGHI ATTUATIVI PREVISTI DAL REGOLAMENTO PRIVACY UE 2016/679 (GDPR)',
   'CORSO DI FORMAZIONE PER I COORDINATORI PER LA PROGETTAZIONE E PER L’ESECUZIONE DEI LAVORI',
   'CORSO PER PATENTINO FITOSANITARI (PRIMO RILASCIO)',
   'CORSO RINNOVO DEL PATENTINO FITOSANITARI',
   'CORSO TEORICO E PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI DI TIPO TRANSPALLET',
   'FORMAZIONE PER L''USO DEI DIISOCIANATI - LIVELLO GENERALE, INTERMEDIO E AVANZATO',
   'FORMAZIONE PER L''USO DEI DIISOCIANATI: LIVELLO GENERALE, INTERMEDIO E AVANZATO',
   'IGIENE ALIMENTI',
   'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO COORDINATORE SICUREZZA)',
   'MV 200 - RODIGGIO',
   'MV 210 - CARRELLI',
   'MV 220 - IMPIANTO PNEUMATICO E FRENO',
   'MV 230 - APPARECCHIATURE DI BORDO PER LO SICUREZZA DELLO CONDOTTA (IPE)',
   'MV 240 - ORGANI DI AGGANCIO E REPULSIONE',
   'MV 250 - IMPIANTISTICA ELETTRICA ED ELETTRONICA (DI BASE, DI POTENZA, DI SEGNALE)',
   'MV 260 - PORTE',
   'MV 270 - TELAIO E CASSA (DISPOSITIVI DI BLOCCO PARTI MOBILI)',
   'MV 280 - IMPIANTO ANTINCENDIO',
   'QUALIFICA SALDATORE',
   'RISCHIO CHIMICO E BIOLOGICO, SANIFICAZIONE DEGLI AMBIENTI DI LAVORO, CORRETTO USO DEI DPI E PROCEDURE ANTICONTAGIO CORONAVIRUS.'
 );

-- DA DECIDERE: lasciati volutamente 'da mappare'. Finche' restano cosi'
-- il contatore non arriva a 0 e C1b resta bloccato: vanno chiusi a mano
-- dalla UI (codice o Ignorato) dopo averli discussi.

commit;

-- verifica: 'damappare' deve valere esattamente il numero dei DA DECIDERE
select count(*) filter (where corso_codice is null and not ignorato) as damappare,
       count(*) filter (where corso_codice is not null and not ignorato) as mappati,
       count(*) filter (where ignorato) as ignorati,
       count(*) as totale
  from corso_alias;
